"""empty message

Revision ID: e850bb5c6c8b
Revises: 98fe705d3d80
Create Date: 2020-04-15 17:51:50.255394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e850bb5c6c8b'
down_revision = '98fe705d3d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permission_value', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.drop_column('role', 'permission_value')
    op.drop_column('role', 'default')
    # ### end Alembic commands ###
